#
# modes.yaml
#
# This file provides multiple choice menu options for prompt templates.
# It overwrites default options included in the PromptFx distribution.
---
translation:
  - Spanish
  - French
  - German
  - Japanese