# Use lists below to override the OpenAI API models shown in PromptFx.
# Leave a list blank to use the defaults.
---
audio: [ gpt-4o-transcribe, gpt-4o-mini-transcribe, whisper-1 ]
chat: [ gpt-3.5-turbo, gpt-4-turbo, gpt-4, o3-mini ]
completion: [ gpt-3.5-turbo-instruct, davinci-002, babbage-002 ]
embeddings: [ text-embedding-ada-002, text-embedding-3-large, text-embedding-3-small ]
moderation: [ omni-moderation-latest ]
# gpt-5 models are not supported in the text/chat API
# multimodal: [ gpt-5.1, gpt-5, gpt-5-mini, gpt-5-nano, gpt-4.1, gpt-4.1-mini, gpt-4.1-nano, gpt-4o, gpt-4o-mini, gpt-4-turbo, o4-mini, o3, o1 ]
multimodal: [ gpt-4.1, gpt-4.1-mini, gpt-4.1-nano, gpt-4o, gpt-4o-mini, gpt-4-turbo, o4-mini, o3, o1 ]
responses: [ o3-pro, o1-pro, gpt-5-pro, gpt-oss-120b, gpt-oss-20b ]
tts: [ gpt-4o-mini-tts, tts-1, tts-1-hd ]
image_generator: [ gpt-image-1, gpt-image-1-mini, dall-e-3, dall-e-2 ]
# gpt-5 models are not supported in the text/chat API
# vision_language: [ gpt-5.1, gpt-5, gpt-5-mini, gpt-5-nano, gpt-4.1, gpt-4.1-mini, gpt-4.1-nano, gpt-4o, gpt-4o-mini, gpt-4-turbo, o4-mini, o3, o1 ]
vision_language: [ gpt-4.1, gpt-4.1-mini, gpt-4.1-nano, gpt-4o, gpt-4o-mini, gpt-4-turbo, o4-mini, o3, o1 ]
